# Generated by rust2rpm-9-1.fc30
%bcond_without check

%global crate fedora-coreos-metrics-client

Name:           rust-%{crate}
Version:        0.1.0
Release:        1%{?dist}
Summary:        Metrics collection client for Fedora CoreOS

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            https://crates.io/crates/fedora-coreos-metrics-client
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
BuildRequires:  (crate(error-chain/default) >= 0.12.1 with crate(error-chain/default) < 0.13.0)
BuildRequires:  (crate(glib/default) >= 0.7.1 with crate(glib/default) < 0.8.0)
BuildRequires:  (crate(log/default) >= 0.4.6 with crate(log/default) < 0.5.0)

%global _description \
Metrics collection client for Fedora CoreOS

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%doc README.md
%{_bindir}/fedora-coreos-metrics-client
%{_unitdir}/fedora-coreos-metrics-client.service
%dir %{_sysconfdir}/fedora-coreos-metrics
%config(noreplace) %{_sysconfdir}/fedora-coreos-metrics/client.conf

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install
%{__install} -Dpm0644 -t %{buildroot}%{_unitdir} \
  systemd/*.service
%{__mkdir_p} %{buildroot}%{_sysconfdir}/fedora-coreos-metrics
%{__install} -Dpm0644 -t %{buildroot}%{_sysconfdir}/fedora-coreos-metrics \
  dist/client.conf

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Mon May 27 04:39:42 UTC 2019 Robert Fairley <rfairley@redhat.com> - 0.1.0-1
- Initial package
